### ISSUE TITLE
Discussion: Use of intermediate graphql file

### ISSUE THREAD

**Issue by dan-silver** [microsoftgraph/graphql-demo#4]
Before reviewing #3, I was wondering if we can discuss the use of an intermediate graphql file?  If I understand the project correctly, it downloads a metadata file, parses it, writes a .graphql file, then reads that file and passes it to `makeExecutableSchema`.

When initially coding this project, did you consider directly creating the graphql objects?  There's [a great example](https://github.com/graphql/graphql-js/blob/master/src/__tests__/starWarsSchema.js) in the graphql-js project of dynamically building a schema rather than reading a graphql file.  I'm wondering if it's simpler to directly map to these types?  So, after parsing the metadata file we have some structure in memory and instead of using that to write a schema to a file we create an in memory map of all the OData types.  For example the mapping would be `Edm.String` to `GraphQLString` and entities would map to `GraphQLObjectType`.

I think we could get rid of a few dependencies like acorn, astring, graphql-tools, etc.  I haven't thought this through all the way, but it might also be easier to use this pattern to add all the other HTTP verbs and OData query parameters.  This also means we could get rid of the `npm run build` step and just have an `npm run start`. The metadata could be downloaded on the first request or on server start.

Are there other advantages to generating a graphql schema file?  If we still want it, there might be a way to have graphql-js export it for us.

**Comment by dpim** [comment]
Sure, I think there are a few advantages of having a stored, generated schema. 
- It provide introspection into the schema (in GraphQL schema language), without requiring you to parse each of the object types. Interfaces, arguments, etc are much more apparent.
- It encourages modularity. For instance, I could see us defining separate schema files for /beta/ and /v1.0/ and patching these together as an executable schema. 
- It allows you to lock to a snapshot of the service at a point in time. This allows integration with tooling for augmenting metadata with annotations.
- It forces keeping consistency between the schema defined and the underlying resolvers. For instance, if we advertise support for a field with arguments, makeExecutableSchema can ensure that the corresponding resolver exists. 
- If we really think that getting rid of the build step makes sense, lazy loading on npm start is possible without requiring a broader overhaul to move to a dynamic model. Also, note that the type mapping you're describing is already happening today (Edm.String to GraphQLString, etc).

**Comment by dan-silver** [comment]
Great points, closing
