### ISSUE TITLE
Not able to search any Site or list using query parameter.

### ISSUE THREAD

**Issue by anomepani** [microsoftgraph/graphql-demo#6]
I would like to fetch all site collection or sub site by searching e.g. sites?Search=Site but it is not working with graphql demo.

Working in this demo : https://graph.microsoft.com/v1.0/sites?Search=BR

Please provide way or some document so I can modify GraphQL Query.

**Comment by dpim** [comment]
I'm not working on this project any more but I can suggest how you could implement the $search query option for sites. You would want to first define search as an argument in the GraphQL schema (perhaps adding a special case [here](https://github.com/microsoftgraph/graphql-demo/blob/master/src/setup.js#L201)). Next, you'll need to do a simple update to the resolution request logic and check for args.search - updating the path appropriately (similar to [how paths with id arguments are constructed](https://github.com/microsoftgraph/graphql-demo/blob/master/src/resolverHelpers.js#L7)). Let me know if you have any questions.

**Comment by anomepani** [comment]
@dpim  Thank you for your help. I have forked repository to [My account](https://github.com/anomepani/graphql-demo) and added support for search param for only 'sites' and added a static condition. As documentation or comments for code are missing that's why not able to add support for 'search' argument for all query.

**Comment by jthake** [comment]
Closing all issues since this repo is being archived and no longer maintained.
