### ISSUE TITLE
Broken link for demo app

### ISSUE THREAD

**Issue by anomepani** [microsoftgraph/graphql-demo#9]
In Readme.md Link for live demo site is broken.
You can verify by clicking on below link which is demo app link as per Readme.md 
 [Try the Microsoft Graph GraphQL Demo here](https://graphql-demo.azurewebsites.net/)

**Comment by tonyxu-io** [comment]
+1. Anyone can comment?

**Comment by jthake** [comment]
Closing all issues since this repo is being archived and no longer maintained.
